sources = [
    {"url": "https://www.meetup.com/code-collective/events/", "group_name": "Code Collective", "orgImageUrl": "/images/codecollective.webp", "tags": ["Code Collective & Partners", "Tech Community", "Community Organizing"]},
    {"url": "https://www.meetup.com/baltimore-tech/events/", "tags": ["Economic Development", "Tech Community"]},
    {"url": "https://www.meetup.com/devops-columbia/events/", "tags": ["Tech Skills", "DevOps", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/baltimore-code-and-coffee/events/", "tags": ["Tech Skills", "Software Development", "Tech Community"]},
    {"url": "https://www.meetup.com/baltimore-cryptomondays/events/", "tags": ["Finance", "Crypto & Web3"]},
    {"url": "https://www.meetup.com/ellicott-city-cryptocurrency-meetup-group/events/", "tags": ["Finance", "Crypto & Web3"]},
    {"url": "https://www.meetup.com/it-social-east-us-ca-data-technology-cybersecurity/events/", "tags": ["Tech Skills", "Cybersecurity", "Data Science", "Tech Community"]},
    {"url": "https://www.meetup.com/the-baltimore-wordpress-group/events/", "tags": ["Tech Skills", "Web Development"]},
    {"url": "https://www.meetup.com/baltimore-bayesians/events/", "tags": ["Tech Skills", "AI", "Data Science"]},
    {"url": "https://www.meetup.com/dataworks/events/", "tags": ["Tech Skills", "Data Science"]},
    {"url": "https://www.meetup.com/baltimorebitcoin/events/", "tags": ["Finance", "Crypto & Web3"]},
    {"url": "https://www.meetup.com/python-frederick/events/", "tags": ["Tech Skills", "Python", "Software Development"]},
    {"url": "https://www.meetup.com/the-business-connection-network/", "tags": ["Business", "Tech Community"]},
    {"url": "https://www.meetup.com/baltimore-ux-meetup/", "tags": ["Tech Skills", "UX", "Product"]},
    {"url": "https://www.meetup.com/baltomsdn/", "tags": ["Tech Skills", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/pitch-labs/", "tags": ["Business"]},
    {"url": "https://www.meetup.com/Baltimore-Hackerspace/", "orgImageUrl": "https://baltimorehackerspace.com/wp-content/uploads/2013/06/bahalogotop.png", "tags": ["Makerspace", "Tech Community"]},
    {"url": "https://www.meetup.com/maryland-red-hat-user-group/", "tags": ["Tech Skills", "DevOps", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/columbia-politics-meetup-group/", "tags": ["Politics"]},
    {"url": "https://www.meetup.com/ai-performance-engineering-washington-dc/", "tags": ["Tech Skills", "AI", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/philanthropicode/", "tags": ["Code Collective & Partners", "Community Organizing", "Tech Community"]},
    {"url": "https://www.meetup.com/profs-and-pints-baltimore/", "tags": ["Business"]},
    {"url": "https://www.meetup.com/ai-enthusiasts/", "tags": ["Tech Skills", "AI"]},
    {"url": "https://www.meetup.com/KMC-Maryland/", "tags": ["Religion"]},
    {"url": "https://www.meetup.com/meditation-modern-buddhism-in-canton/", "tags": ["Religion"]},
    {"url": "https://www.meetup.com/baltimore-tech-innovation/", "tags": ["Economic Development"]},
    {"url": "https://www.meetup.com/cmap-online/", "tags": ["Business"]},
    {"url": "https://www.meetup.com/cyber-steam-global-innovation-alliance/", "tags": ["Tech Skills", "Cybersecurity"]},
    {"url": "https://www.meetup.com/marylandforwardparty/", "tags": ["Politics"]},
    {"url": "https://www.meetup.com/charm-city-angels-capital-coffee/", "tags": ["Finance"]},
    {"url": "https://www.meetup.com/baltimore-black-techies-meetup/", "tags": ["Economic Development", "Tech Community", "Community Organizing"]},
    {"url": "https://www.eventbrite.com/e/tential-tech-tuesday-tickets-1366415157519", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/e/techspo-baltimore-2025-technology-expo-internet-adtech-martech-tickets-1114708064829", "tags": ["Business", "Tech Community", "Startup"]},
    {"url": "https://www.eventbrite.com/e/2025-md-makerspace-meetup-tickets-1345760890049", "tags": ["Makerspace"]},
    {"url": "https://www.eventbrite.com/e/baltimore-data-day-state-of-our-neighborhoods-2025-tickets-1424508315719", "tags": ["Economic Development"]},
    {"url": "https://www.eventbrite.com/e/energyconnect-virtual-job-networking-hub-for-energy-professionals-baltimore-tickets-1434086875449", "tags": ["Infrastructure"]},
    {"url": "https://www.eventbrite.com/o/blk-tech-connect-107618183651", "tags": ["Economic Development", "Tech Community"]},
    {"url": "https://www.eventbrite.com/o/open-works-86343210063", "orgImageUrl": "https://www.openworksbmore.org/wp-content/uploads/2021/04/openworks-logo.svg", "tags": ["Makerspace"]},
    {"url": "https://www.eventbrite.com/o/baltimore-under-ground-science-space-bugss-4318633291", "orgImageUrl": "https://bugssonline.org/wp-content/themes/BUGS3/assets/images/bugsslogo-square300.png", "tags": ["Makerspace"]},
    {"url": "https://www.eventbrite.com.au/o/it-social-baltimore-110781946041", "tags": ["Tech Skills", "Cybersecurity", "Data Science", "Tech Community"]},
    {"url": "https://www.eventbrite.com/cc/baltimore-4326703", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/o/impact-hub-baltimore-8423440202", "orgImageUrl": "https://baltimore.impacthub.net/favicon.ico", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/o/a-prosperous-tomorrow-11875462384", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/o/lets-go-113135073431", "tags": ["Economic Development"]},
    {"url": "https://www.eventbrite.com/o/howard-county-office-of-workforce-development-88843319173", "tags": ["Economic Development"]},
    {"url": "https://www.eventbrite.com/o/howard-county-economic-development-authority-2805856464", "tags": ["Economic Development"]},
    {"url": "https://www.eventbrite.com/o/rmi-107139765", "tags": ["Water"]},
    {"url": "https://www.eventbrite.com/o/nachman-executive-consulting-77249254883", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/o/vashtiblue-jewelry-studio-120729155482", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/o/baltimore-robotics-center-14997527925", "orgImageUrl": "https://www.baltimoreroboticscenter.com/wp-content/uploads/2021/02/cropped-Balto-Robotics-CTR-logo-new.png", "tags": ["Makerspace", "Robotics"]},
    {"url": "https://www.eventbrite.com/o/fight-blight-bmore-18309938620", "tags": ["Water"]},
    {"url": "https://www.eventbrite.com/o/79181486483", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/o/34179073381", "tags": ["Business"]},
    {"url": "https://www.eventbrite.com/o/11070919734", "tags": ["Business"]},
    {"url": "https://luma.com/2d1a4uwv", "tags": ["Business"]},
    {"url": "https://lu.ma/calendar/cal-vzms1nGZmYUUCrj", "tags": ["Water"]},
    {"url": "https://lu.ma/Bmore_Climate", "tags": ["Water", "Tech Community"]},
    {"url": "https://luma.com/blk-tech-connect-baltimore", "tags": ["Economic Development", "Tech Community", "Community Organizing"]},
    {"url": "https://lu.ma/user/charmcityjs", "tags": ["Tech Skills", "JavaScript", "Software Development"]},
    {"url": "https://lu.ma/mtechumd", "tags": ["Economic Development"]},
    {"url": "https://luma.com/calendar/cal-MVw6HVCN4MEFaNV", "tags": ["Economic Development"]},
    {"url": "https://luma.com/codecollective", "group_name": "Code Collective", "orgImageUrl": "/images/codecollective.webp", "tags": ["Code Collective & Partners", "Tech Community", "Community Organizing"]},
    {"url": "https://luma.com/bmore-on-rails", "tags": ["Tech Skills", "Ruby", "Software Development"]},
    {"url": "https://luma.com/LetsBMore", "tags": ["Economic Development", "Tech Community"]},
    {"url": "https://luma.com/MEIA", "tags": ["Economic Development"]},
    {"url": "https://luma.com/umbcche", "tags": ["Business"]},
    {"url": "https://luma.com/SGLang-meetups", "tags": ["Tech Skills", "AI"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-d4s75dZyC9VOXAd", "tags": ["Business"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-iZFykYNctUzTFLd", "tags": ["Economic Development"]},
    {"url": "https://baltimoresistercities.org/events/", "tags": ["Community", "Tech Community"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-A83YmR5Onz1uMdp", "group_name": "Web3 Maryland", "orgImageUrl": "https://images.lumacdn.com/avatars/4g/431276ef-4081-4db7-a077-9a45da105826.png", "tags": ["Finance", "Crypto & Web3", "Tech Skills", "AI", "Economic Development", "Tech Community"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-k0oO7FswDxbAWh0", "tags": ["Business"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-cTlmPNsi6jHYweP", "tags": ["Business"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-2eWBPcn6lj9Dzqz", "tags": ["Tech Community"]},
    {"url": "http://docs.google.com/forms/d/e/1FAIpQLSfAHwexta7vxLto1xmvBxFNawicAUtRrjTKqN0jHs25RjLCQg/viewform", "tags": ["Business"]},
    {"url": "https://gdg.community.dev/chapter/3047", "tags": ["Code Collective & Partners", "Tech Community", "Software Development"], "chapter_id": 3047},
]
