version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node --version
      - npm --version
      - git submodule update --init --recursive
      - cd r8-rowhome
      - npm ci

  build:
    commands:
      - npx vite build --base=/r8-rowhome/
      - cd ..
      - mkdir -p pipeline-output/source
      - mkdir -p pipeline-output/r8-rowhome
      - rsync -a --exclude pipeline-output ./ pipeline-output/source/
      - rsync -a r8-rowhome/dist/ pipeline-output/r8-rowhome/

artifacts:
  base-directory: pipeline-output
  files:
    - '**/*'