sources = {
    "Meetup":[
        "https://www.meetup.com/code-collective/events/",
        "https://www.meetup.com/baltimore-tech/events/",
        "https://www.meetup.com/devops-columbia/events/",
        "https://www.meetup.com/baltimore-code-and-coffee/events/",
        #"https://www.meetup.com/baltimore-indie-game-developers-group/events/",
        "https://www.meetup.com/baltimore-cryptomondays/events/",
        "https://www.meetup.com/ellicott-city-cryptocurrency-meetup-group/events/",
        "https://www.meetup.com/it-social-east-us-ca-data-technology-cybersecurity/events/",
        "https://www.meetup.com/the-baltimore-wordpress-group/events/",
        "https://www.meetup.com/baltimore-bayesians/events/",
        "https://www.meetup.com/dataworks/events/",
        "https://www.meetup.com/baltimorebitcoin/events/",
        "https://www.meetup.com/python-frederick/events/",
        "https://www.meetup.com/the-business-connection-network/",
        "https://www.meetup.com/baltimore-ux-meetup/",
        "https://www.meetup.com/baltomsdn/",
        "https://www.meetup.com/pitch-labs/",
        "https://www.meetup.com/Baltimore-Hackerspace/",
        "https://www.meetup.com/maryland-red-hat-user-group/",
        "https://www.meetup.com/columbia-politics-meetup-group/",
        "https://www.meetup.com/dc-area-drone-user-group/",
        "https://www.meetup.com/ai-performance-engineering-washington-dc/",
        "https://www.meetup.com/philanthropicode/"
    ],
    "Eventbrite":[
        "https://www.eventbrite.com/e/tential-tech-tuesday-tickets-1366415157519",
        "https://www.eventbrite.com/e/techspo-baltimore-2025-technology-expo-internet-adtech-martech-tickets-1114708064829",
        "https://www.eventbrite.com/e/2025-md-makerspace-meetup-tickets-1345760890049",
        "https://www.eventbrite.com/e/baltimore-data-day-state-of-our-neighborhoods-2025-tickets-1424508315719"
    ],
    "Eventbrite Orgs":[
        "https://www.eventbrite.com/o/blk-tech-connect-107618183651",
        "https://www.eventbrite.com/o/open-works-86343210063",
        "https://www.eventbrite.com/o/baltimore-under-ground-science-space-bugss-4318633291",
        "https://www.eventbrite.com.au/o/it-social-baltimore-110781946041",
        "https://www.eventbrite.com/cc/baltimore-4326703",
        "https://www.eventbrite.com/o/impact-hub-baltimore-8423440202",
        "https://www.eventbrite.com/o/a-prosperous-tomorrow-11875462384"
    ],
    "Jotform":[
        #"https://form.jotform.com/251063812795157"
    ],
    "Luma":[
        "https://lu.ma/k5mgdolz",
        "https://lu.ma/02zv4one"
    ],
    "Luma Orgs":[
        "https://lu.ma/civic-tech-dc",
        "https://lu.ma/calendar/cal-vzms1nGZmYUUCrj",
        "https://lu.ma/Bmore_Climate",
        "https://lu.ma/blktechconnect",
        "https://lu.ma/user/web3dc"
    ],
    "Luma Users":[
        #"https://api.lu.ma/user/profile/events-hosting"
        "usr-tYdFPQYBiZY4T6B",
        "usr-d4s75dZyC9VOXAd",
        "usr-iZFykYNctUzTFLd"
    ],
    "Google Forms":[
        "http://docs.google.com/forms/d/e/1FAIpQLSfAHwexta7vxLto1xmvBxFNawicAUtRrjTKqN0jHs25RjLCQg/viewform"
    ]
}