sources = {
    "Meetup":[
        "https://www.meetup.com/code-collective/events/",
        "https://www.meetup.com/baltimore-tech/events/",
        "https://www.meetup.com/devops-columbia/events/",
        "https://www.meetup.com/baltimore-code-and-coffee/events/",
        "https://www.meetup.com/baltimore-indie-game-developers-group/events/",
        "https://www.meetup.com/baltimore-cryptomondays/events/",
        "https://www.meetup.com/ellicott-city-cryptocurrency-meetup-group/events/",
        "https://www.meetup.com/it-social-east-us-ca-data-technology-cybersecurity/events/",
        "https://www.meetup.com/the-baltimore-wordpress-group/events/",
        "https://www.meetup.com/baltimore-bayesians/events/",
        "https://www.meetup.com/dataworks/events/",
        "https://www.meetup.com/baltimorebitcoin/events/",
        "https://www.meetup.com/python-frederick/events/"
    ],
    "Eventbrite":[
        "https://www.eventbrite.com/e/indie-game-fest-2025-tickets-1264402364509",
        "https://www.eventbrite.com/e/canton-laughs-the-inaugural-comedy-showcase-tickets-1354002962309",
        "https://www.eventbrite.com/e/people-make-games-developer-talk-tickets-1264411943159",
        "https://www.eventbrite.com/e/county-executive-balls-5th-annual-stem-awards-tickets-1371704919339",
        "https://www.eventbrite.com/e/tential-tech-tuesday-tickets-1366415157519",
        "https://www.eventbrite.com/e/weekly-meetings-no-labels-party-us-2028-tickets-1375290293289",
        "https://www.eventbrite.com/e/know-your-local-leaders-tickets-1302421310199",
        "https://www.eventbrite.com/e/weekly-meetings-no-labels-party-us-2028-tickets-1375290313349",
        "https://www.eventbrite.com/e/techspo-baltimore-2025-technology-expo-internet-adtech-martech-tickets-1114708064829",
        "https://www.eventbrite.com/e/2025-md-makerspace-meetup-tickets-1345760890049",
        "https://www.eventbrite.com/e/blk-tech-connect-3-black-tech-brunch-tickets-1403222709899"
    ],
    "Jotform":[
        "https://form.jotform.com/251063812795157"
    ],
    "Luma":[
        "https://lu.ma/k5mgdolz",
        "https://lu.ma/wrqpk3v2",
        "https://lu.ma/02zv4one"
    ],
}