categories = [
    "Tech Skills",
    "Economic Development",
    "Infrastructure",
    "Makerspace",
    "Business",
    "Politics",
    "Finance",
    "Code Collective & Partners",
]
tag_rules_url = [
  # Domain-based rules
  ("tedcomd.com", ["Economic Development"]),
  ("eventbrite.com", ["Business"]),
  ("meetup.com", ["Economic Development"]),
  ("lu.ma", ["Business"]),
  ("innovationmaryland.org", ["Economic Development"]),
  ("gdg.community.dev", ["Code Collective & Partners"]),
  ("unallocatedspace.org", ["Makerspace"]),
  ("baltimorenode.org", ["Tech Skills"]),
  ("bwtech.umbc.edu", ["Economic Development"]),
  ("members.mdtechcouncil.com", ["Business"]),
  ("bugss.org", ["Makerspace"]),
  ("digitalequitybaltimore.org", ["Economic Development"]),
  ("baltimoreindiegames.com", ["Makerspace"]),
  ("profsandpints.com", ["Education"]),
  ("wsscwater.com", ["Infrastructure"]),
  ("gbc.org", ["Business"]),
  ("dc443.org", ["Tech Skills"]),
  
  # Content-based rules (matching within URLs)
  ("wordpress", ["Tech Skills"]),
  ("python", ["Tech Skills"]),
  ("node", ["Tech Skills"]),
  ("javascript", ["Tech Skills"]),
  ("gdg", ["Code Collective & Partners"]),
  ("ai", ["Tech Skills"]),
  ("cyber", ["Tech Skills"]),
  ("security", ["Tech Skills"]),
  ("hack", ["Tech Skills"]),
  ("infosec", ["Tech Skills"]),
  ("climate", ["Infrastructure"]),
  ("crypto", ["Finance"]),
  ("bitcoin", ["Finance"]),
  ("web3", ["Finance"]),
  ("blockchain", ["Finance"]),
  ("defcon", ["Tech Skills"]),
  ("iot", ["Makerspace"]),
  ("drone", ["Makerspace"]),
  ("robotics", ["Makerspace"]),
  ("game", ["Makerspace"]),
  ("gaming", ["Makerspace"]),
  ("stem", ["Tech Skills"]),
  ("biology", ["Tech Skills"]),
  ("biotech", ["Business"]),
  ("igem", ["Tech Skills"]),
  ("science", ["Tech Skills"]),
  ("synthetic", ["Tech Skills"]),
  ("dna", ["Tech Skills"]),
  ("genetic", ["Tech Skills"]),
  ("cell", ["Business"]),
  ("medical", ["Business"]),
  ("health", ["Business"]),
  ("manufacturing", ["Business"]),
  ("cleanroom", ["Business"]),
  ("biotherapeutics", ["Business"]),
  ("therapy", ["Business"]),
  ("accelerator", ["Business"]),
  ("startup", ["Business"]),
  ("entrepreneur", ["Business"]),
  ("pitch", ["Business"]),
  ("venture", ["Business"]),
  ("investment", ["Finance"]),
  ("investor", ["Finance"]),
  ("funding", ["Finance"]),
  ("angel", ["Finance"]),
  ("bridge", ["Finance"]),
  ("tax", ["Finance"]),
  ("accounting", ["Finance"]),
  ("finance", ["Finance"]),
  ("procurement", ["Business"]),
  ("vendor", ["Business"]),
  ("contract", ["Business"]),
  ("small-business", ["Business"]),
  ("minority-business", ["Business"]),
  ("wbe", ["Business"]),
  ("chamber", ["Business"]),
  ("chamber-of-commerce", ["Business"]),
  ("bizcon", ["Business"]),
  ("expo", ["Business"]),
  ("conference", ["Business"]),
  ("summit", ["Business"]),
  ("workshop", ["Tech Skills"]),
  ("webinar", ["Tech Skills"]),
  ("training", ["Tech Skills"]),
  ("education", ["Tech Skills"]),
  ("course", ["Tech Skills"]),
  ("breakfast", ["Business"]),
  ("lunch", ["Business"]),
  ("mixer", ["Business"]),
  ("happy-hour", ["Business"]),
  ("networking", ["Business"]),
  ("yoga", ["Wellness"]),
  ("meditation", ["Wellness"]),
  ("transportation", ["Infrastructure"]),
  ("water", ["Infrastructure"]),
  ("energy", ["Infrastructure"]),
  ("electric", ["Infrastructure"]),
  ("power", ["Infrastructure"]),
  ("climate-tech", ["Infrastructure"]),
  ("real-estate", ["Business"]),
  ("construction", ["Business"]),
  ("building", ["Business"]),
  ("government", ["Politics"]),
  ("policy", ["Politics"]),
  ("advocacy", ["Politics"]),
  ("annapolis", ["Politics"]),
  ("state", ["Politics"]),
  ("legal", ["Business"]),
  ("law", ["Business"]),
  ("attorney", ["Business"]),
  ("marketing", ["Business"]),
  ("sales", ["Business"]),
  ("brand", ["Business"]),
  ("creative", ["Business"]),
  ("design", ["Tech Skills"]),
  ("ux", ["Tech Skills"]),
  ("ui", ["Tech Skills"]),
  ("devops", ["Tech Skills"]),
  ("cloud", ["Tech Skills"]),
  ("aws", ["Tech Skills"]),
  ("azure", ["Tech Skills"]),
  ("gcp", ["Tech Skills"]),
  ("kubernetes", ["Tech Skills"]),
  ("docker", ["Tech Skills"]),
  ("react", ["Tech Skills"]),
  ("vue", ["Tech Skills"]),
  ("angular", ["Tech Skills"]),
  ("typescript", ["Tech Skills"]),
  ("java", ["Tech Skills"]),
  ("c#", ["Tech Skills"]),
  ("c++", ["Tech Skills"]),
  ("go", ["Tech Skills"]),
  ("rust", ["Tech Skills"]),
  ("swift", ["Tech Skills"]),
  ("kotlin", ["Tech Skills"]),
  ("php", ["Tech Skills"]),
  ("ruby", ["Tech Skills"]),
  ("rails", ["Tech Skills"]),
  ("django", ["Tech Skills"]),
  ("flask", ["Tech Skills"]),
  ("spring", ["Tech Skills"]),
  ("laravel", ["Tech Skills"]),
  ("sql", ["Tech Skills"]),
  ("nosql", ["Tech Skills"]),
  ("mongodb", ["Tech Skills"]),
  ("postgresql", ["Tech Skills"]),
  ("mysql", ["Tech Skills"]),
  ("redis", ["Tech Skills"]),
  ("elasticsearch", ["Tech Skills"]),
  ("kafka", ["Tech Skills"]),
  ("rabbitmq", ["Tech Skills"]),
  ("graphql", ["Tech Skills"]),
  ("rest", ["Tech Skills"]),
  ("api", ["Tech Skills"]),
  ("microservices", ["Tech Skills"]),
  ("serverless", ["Tech Skills"]),
  ("ml", ["Tech Skills"]),
  ("machine-learning", ["Tech Skills"]),
  ("deep-learning", ["Tech Skills"]),
  ("nlp", ["Tech Skills"]),
  ("computer-vision", ["Tech Skills"]),
  ("data-science", ["Tech Skills"]),
  ("analytics", ["Tech Skills"]),
  ("big-data", ["Tech Skills"]),
  ("etl", ["Tech Skills"]),
  ("data-engineering", ["Tech Skills"]),
  ("devsecops", ["Tech Skills"]),
  ("sre", ["Tech Skills"]),
  ("git", ["Tech Skills"]),
  ("ci-cd", ["Tech Skills"]),
  ("jenkins", ["Tech Skills"]),
  ("github", ["Tech Skills"]),
  ("gitlab", ["Tech Skills"]),
  ("bitbucket", ["Tech Skills"]),
  ("jira", ["Tech Skills"]),
  ("agile", ["Tech Skills"]),
  ("scrum", ["Tech Skills"]),
  ("kanban", ["Tech Skills"]),
  ("tdd", ["Tech Skills"]),
  ("bdd", ["Tech Skills"]),
  ("testing", ["Tech Skills"]),
  ("qa", ["Tech Skills"]),
  ("automation", ["Tech Skills"]),
  ("mobile", ["Tech Skills"]),
  ("ios", ["Tech Skills"]),
  ("android", ["Tech Skills"]),
  ("flutter", ["Tech Skills"]),
  ("react-native", ["Tech Skills"]),
  ("xamarin", ["Tech Skills"]),
  ("ionic", ["Tech Skills"]),
  ("cordova", ["Tech Skills"]),
  ("pwa", ["Tech Skills"]),
  ("webassembly", ["Tech Skills"]),
  ("wasm", ["Tech Skills"]),
  ("electron", ["Tech Skills"]),
  ("desktop", ["Tech Skills"]),
  ("embedded", ["Makerspace"]),
  ("arduino", ["Makerspace"]),
  ("raspberry-pi", ["Makerspace"]),
  ("esp32", ["Makerspace"]),
  ("microcontroller", ["Makerspace"]),
  ("sensor", ["Makerspace"]),
  ("actuator", ["Makerspace"]),
  ("3d-printing", ["Makerspace"]),
  ("cnc", ["Makerspace"]),
  ("laser-cutter", ["Makerspace"]),
  ("woodworking", ["Makerspace"]),
  ("metalworking", ["Makerspace"]),
  ("electronics", ["Makerspace"]),
  ("circuit", ["Makerspace"]),
  ("pcb", ["Makerspace"]),
  ("soldering", ["Makerspace"]),
  ("welding", ["Makerspace"]),
  ("textiles", ["Makerspace"]),
  ("sewing", ["Makerspace"]),
  ("knitting", ["Makerspace"]),
  ("ceramics", ["Makerspace"]),
  ("glassblowing", ["Makerspace"]),
  ("jewelry", ["Makerspace"]),
  ("blacksmithing", ["Makerspace"]),
  ("leatherworking", ["Makerspace"]),
  ("printmaking", ["Makerspace"]),
  ("pottery", ["Makerspace"]),
  ("sculpture", ["Makerspace"]),
  ("painting", ["Makerspace"]),
  ("drawing", ["Makerspace"]),
  ("photography", ["Makerspace"]),
  ("videography", ["Makerspace"]),
  ("audio", ["Makerspace"]),
  ("music", ["Makerspace"]),
  ("podcast", ["Makerspace"]),
  ("streaming", ["Makerspace"]),
  ("vr", ["Makerspace"]),
  ("ar", ["Makerspace"]),
  ("xr", ["Makerspace"]),
  ("metaverse", ["Makerspace"]),
  ("quantum", ["Tech Skills"]),
  ("quantum-computing", ["Tech Skills"]),
  ("defi", ["Finance"]),
  ("nft", ["Finance"]),
  ("dao", ["Finance"]),
  ("smart-contract", ["Finance"]),
  ("ethereum", ["Finance"]),
  ("solana", ["Finance"]),
  ("cardano", ["Finance"]),
  ("polkadot", ["Finance"]),
  ("cosmos", ["Finance"]),
  ("avalanche", ["Finance"]),
  ("polygon", ["Finance"]),
  ("optimism", ["Finance"]),
  ("arbitrum", ["Finance"]),
  ("zksync", ["Finance"]),
  ("starknet", ["Finance"]),
  ("rollup", ["Finance"]),
  ("layer2", ["Finance"]),
  ("sidechain", ["Finance"]),
  ("oracle", ["Finance"]),
  ("staking", ["Finance"]),
  ("yield", ["Finance"]),
  ("liquidity", ["Finance"]),
  ("amm", ["Finance"]),
  ("dex", ["Finance"]),
  ("cex", ["Finance"]),
  ("custody", ["Finance"]),
  ("wallet", ["Finance"]),
  ("mining", ["Finance"]),
  ("validator", ["Finance"]),
  ("consensus", ["Finance"]),
  ("proof-of-work", ["Finance"]),
  ("proof-of-stake", ["Finance"]),
  ("proof-of-authority", ["Finance"]),
  ("proof-of-history", ["Finance"]),
  ("byzantine", ["Finance"]),
  ("distributed", ["Finance"]),
  ("decentralized", ["Finance"]),
  ("permissionless", ["Finance"]),
  ("trustless", ["Finance"]),
  ("immutable", ["Finance"]),
  ("transparent", ["Finance"]),
  ("auditable", ["Finance"]),
  ("verifiable", ["Finance"]),
  ("composable", ["Finance"]),
  ("interoperable", ["Finance"]),
  ("scalable", ["Finance"]),
  ("secure", ["Finance"]),
  ("private", ["Finance"]),
  ("anonymous", ["Finance"]),
  ("pseudonymous", ["Finance"]),
  ("sybil-resistant", ["Finance"]),
  ("censorship-resistant", ["Finance"]),
  ("sovereign", ["Finance"]),
  ("self-custody", ["Finance"]),
  ("self-sovereign", ["Finance"]),
  ("digital-identity", ["Finance"]),
  ("verifiable-credentials", ["Finance"]),
  ("soulbound-tokens", ["Finance"]),
  ("reputation", ["Finance"]),
  ("governance", ["Finance"]),
  ("voting", ["Finance"]),
  ("treasury", ["Finance"]),
  ("grant", ["Finance"]),
  ("bounty", ["Finance"]),
  ("airdrop", ["Finance"]),
  ("token", ["Finance"]),
  ("coin", ["Finance"]),
  ("stablecoin", ["Finance"]),
  ("algorithmic-stablecoin", ["Finance"]),
  ("collateralized-stablecoin", ["Finance"]),
  ("fiat-backed-stablecoin", ["Finance"]),
  ("commodity-backed-stablecoin", ["Finance"]),
  ("crypto-backed-stablecoin", ["Finance"]),
  ("hybrid-stablecoin", ["Finance"]),
  ("central-bank-digital-currency", ["Finance"]),
  ("cbdc", ["Finance"]),
  ("digital-dollar", ["Finance"]),
  ("digital-euro", ["Finance"]),
  ("digital-yuan", ["Finance"]),
  ("digital-yen", ["Finance"]),
  ("digital-pound", ["Finance"]),
  ("digital-won", ["Finance"]),
  ("digital-rupee", ["Finance"]),
  ("digital-real", ["Finance"]),
  ("digital-peso", ["Finance"]),
  ("digital-lira", ["Finance"]),
  ("digital-rand", ["Finance"]),
  ("digital-naira", ["Finance"]),
  ("digital-cedi", ["Finance"]),
  ("digital-shilling", ["Finance"]),
  ("digital-dirham", ["Finance"]),
  ("digital-riyal", ["Finance"]),
  ("digital-dinar", ["Finance"]),
  ("digital-ringgit", ["Finance"]),
  ("digital-baht", ["Finance"]),
  ("digital-rupiah", ["Finance"]),
  ("digital-sol", ["Finance"]),
  ("digital-bolivar", ["Finance"]),
  ("digital-gourde", ["Finance"]),
]