from city_source_taxonomy import apply_city_source_taxonomy

sources = [
    {"url": "https://www.meetup.com/dc-area-drone-user-group/", "tags": ["Tech Skills", "Robotics"]},
    {"url": "https://www.meetup.com/ai-performance-engineering-washington-dc/", "tags": ["Tech Skills", "AI", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/lfdt-washington-dc/", "tags": ["Tech Community"]},
    {"url": "https://www.meetup.com/openanalyticsdc/", "tags": ["Tech Skills", "Data Science"]},
    {"url": "https://www.meetup.com/meetup-group-xfwllgfg/", "tags": ["Economic Development"]},
    {"url": "https://www.meetup.com/bethesda-ted-talk-discussion-club/", "tags": ["Education", "Community"]},
    {"url": "https://www.meetup.com/washington-area-unity3d-users-group/", "tags": ["Tech Skills", "Game Development"]},
    {"url": "https://www.meetup.com/dc-code-coffee/", "tags": ["Tech Skills", "Software Development", "Tech Community"]},
    {"url": "https://www.meetup.com/dcprofessonals/", "tags": ["Economic Development", "Professional Networking"]},
    {"url": "https://www.meetup.com/microsoft-cloud/", "tags": ["Tech Skills", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/geo-dc/", "tags": ["Tech Skills", "Data Science"]},
    {"url": "https://www.meetup.com/cybersecurity-innovation-forum/", "tags": ["Tech Skills", "Cybersecurity"]},
    {"url": "https://www.meetup.com/platform-engineers-washington-dc/", "tags": ["Tech Skills", "Cloud & Platform", "DevOps"]},
    {"url": "https://www.meetup.com/washington-dc-cyber-security-for-control-systems/", "tags": ["Tech Skills", "Cybersecurity"]},
    {"url": "https://www.meetup.com/producttank-washington-dc/", "tags": ["Tech Skills", "Product", "UX"]},
    {"url": "https://www.meetup.com/dc-ai-llms/", "tags": ["Tech Skills", "AI"]},
    {"url": "https://www.meetup.com/sierradc/", "tags": ["Infrastructure"]},
    {"url": "https://www.meetup.com/carbonfreedc/", "tags": ["Infrastructure"]},
    {"url": "https://www.eventbrite.com/o/tech-turn-up-32326719035", "tags": ["Tech Community"]},
    {"url": "https://www.eventbrite.com/o/georgetown-ventures-61649666833", "tags": ["Business", "Startup"]},
    {"url": "https://www.eventbrite.com/o/georgetown-entrepreneurship-initiative-23347332259", "tags": ["Business", "Startup"]},
    {"url": "https://www.eventbrite.com/e/power-shift-a-der-showcase-tickets-1976198206032", "tags": ["Infrastructure"]},
    {"url": "https://www.eventbrite.com/e/healthy-homes-fair-2026-tickets-1975247546584", "tags": ["Infrastructure"]},
    {"url": "https://www.eventbrite.com/e/want-a-healthier-more-efficient-home-get-coached-tickets-1975244953829", "tags": ["Infrastructure"]},
    {"url": "https://luma.com/climatedraft-community", "group_name": "Climate Draft Community", "orgImageUrl": "https://images.lumacdn.com/cdn-cgi/image/format=auto,fit=cover,width=100,height=100/calendar-covers/0d/0dd0b2e6-0e34-4e4a-ac8a-3ee5ca69efea", "tags": ["Infrastructure", "Community Organizing", "Climate"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-Kwz0Nj6rc80jQ3D", "group_name": "DC Climate Week", "orgImageUrl": "https://images.lumacdn.com/avatars/ln/f11ce87e-b740-4c3a-9cac-b7398062aa10.png", "tags": ["Infrastructure", "Community Organizing"]},
    {"url": "https://lu.ma/civic-tech-dc", "tags": ["Civic Tech", "Tech Community", "Politics"]},
    {"url": "https://luma.com/FounderSpeakeasy", "tags": ["Business", "Startup"]},
    {"url": "https://luma.com/defense-tech-dc", "tags": ["Tech Skills", "Startup", "Tech Community"]},
    {"url": "https://luma.com/DC2", "tags": ["Tech Community"]},
    {"url": "https://luma.com/girliesintechdinner", "tags": ["Tech Community", "Community Organizing"]},
    {"url": "https://luma.com/ai-discussion-club", "tags": ["Tech Skills", "AI"]},
    {"url": "https://luma.com/DCTechMeetup", "tags": ["Tech Community"]},
    {"url": "https://luma.com/vcdc", "tags": ["Startup", "Business"]},
    {"url": "https://luma.com/squadra", "tags": ["Tech Skills", "AI"]},
    {"url": "https://luma.com/filed-events", "tags": ["Tech Community", "Startup"]},
    {"url": "https://luma.com/pgpforcrypto", "tags": ["Finance", "Crypto & Web3"]},
    {"url": "https://luma.com/bitcoindistrict", "tags": ["Finance", "Crypto & Web3"]},
    {"url": "https://luma.com/stationdc", "tags": ["Startup", "Business"]},
    {"url": "https://luma.com/theupskillinglabs", "tags": ["Tech Community", "Career Growth"]},
    {"url": "https://luma.com/aic-dc-2-9", "tags": ["Tech Skills", "AI"]},
    {"url": "https://luma.com/dcnightowls", "tags": ["Tech Community"]},
    {"url": "https://luma.com/seecinstitute", "tags": ["Tech Skills", "Cybersecurity"]},
    {"url": "https://lu.ma/user/web3dc", "tags": ["Finance", "Crypto & Web3", "Tech Community"]},
    {"url": "https://luma.com/dc-ai-lab", "tags": ["Tech Skills", "AI"]},
    {"url": "https://luma.com/6qp0g9bn", "tags": ["Infrastructure"]},
    {"url": "https://luma.com/ab42825w", "tags": ["Infrastructure"]},
    {"url": "https://luma.com/sk5cwpyl", "tags": ["Infrastructure"]},
    {"url": "https://luma.com/zn8l2ayu", "tags": ["Infrastructure"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-f5X9pGAJt2YOugC", "tags": ["Tech Community", "Startup"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-tYdFPQYBiZY4T6B", "tags": ["Economic Development", "Business"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-zbARQX9qqtQoF6E", "tags": ["Tech Skills", "AI"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-dwIy5y3nhtspeEz", "tags": ["Tech Skills", "Product"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-dH29J9OUY8BFf5c", "tags": ["Tech Skills", "Cybersecurity"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-axOGhc5qFBuE3Zz", "tags": ["Tech Community"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-3pgVKlDt94iMvRx", "tags": ["Finance", "Crypto & Web3"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-rEFlkqAdGOtbeWS", "tags": ["Tech Skills", "AI"]},
    {"url": "https://www.meetup.com/women-and-gender-expansive-coders-dc-wgxc-dc/", "tags": ["Tech Skills", "AI"]},

]

apply_city_source_taxonomy(sources)
