from city_source_taxonomy import apply_city_source_taxonomy

sources = [
    {"url": "https://www.meetup.com/lansdale-computer-software-meetup-group", "tags": ["Tech Skills", "Software Development"]},
    {"url": "https://www.meetup.com/appy-hour-test-new-indie-apps", "tags": ["Tech Skills", "Software Development", "Tech Community"]},
    {"url": "https://www.meetup.com/TechinMotionPhilly", "tags": ["Tech Community", "Professional Networking"]},
    {"url": "https://www.meetup.com/eth-philly", "tags": ["Finance", "Crypto & Web3", "Tech Community"]},
    {"url": "https://www.meetup.com/saas_tech_growth_meetup", "tags": ["Business", "Startup", "Tech Community"]},
    {"url": "https://www.meetup.com/mainline-tech-meetup", "tags": ["Tech Community"]},
    {"url": "https://www.meetup.com/philly-hardware", "tags": ["Tech Skills", "Makerspace"]},
    {"url": "https://www.meetup.com/Philadelphia-Cyber-Security-for-Control-Systems", "tags": ["Tech Skills", "Cybersecurity"]},
    {"url": "https://www.meetup.com/phillybricks-philadelphia-databricks-user-group", "tags": ["Tech Skills", "Data Science"]},
    {"url": "https://www.meetup.com/forge-philly", "tags": ["Tech Community", "Startup"]},
    {"url": "https://www.meetup.com/ai-safety-awareness-group-philadelphia", "tags": ["Tech Skills", "AI"]},
    {"url": "https://www.meetup.com/ladies-that-ux-philadelphia", "tags": ["Tech Skills", "UX", "Tech Community"]},
    {"url": "https://www.meetup.com/philly-tech-community", "tags": ["Tech Community"]},
    {"url": "https://www.meetup.com/gdg-philly", "tags": ["Tech Skills", "Tech Community"]},
    {"url": "https://www.meetup.com/Mid-Atlantic-Computational-Chemistry-MACC", "tags": ["Tech Skills", "Science"]},
    {"url": "https://www.meetup.com/ai-philly/", "tags": ["Tech Skills", "AI", "Tech Community"]},
    {"url": "https://www.meetup.com/philly-data-and-ai/", "tags": ["Tech Skills", "Data Science", "AI"]},
    {"url": "https://www.meetup.com/philly-ai-connect/", "tags": ["Tech Skills", "AI", "Tech Community"]},
    {"url": "https://www.meetup.com/philadelphia-ai-user-group/", "tags": ["Tech Skills", "AI"]},
    {"url": "https://www.meetup.com/phillypug/", "tags": ["Tech Skills", "Python", "Software Development"]},
    {"url": "https://www.meetup.com/philadelphia-devops-group/", "tags": ["Tech Skills", "DevOps", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/Philadelphia-Wilmington-AWS-Cloud-Meetup/", "tags": ["Tech Skills", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/philadelphia-linux-user-group-meetup/", "tags": ["Tech Skills", "DevOps", "Open Source"]},
    {"url": "https://www.meetup.com/owasp-philadelphia-chapter/", "tags": ["Tech Skills", "Cybersecurity"]},
    {"url": "https://www.meetup.com/Women-in-Cybersecurity-Cyberjutsu-Philly/", "tags": ["Tech Skills", "Cybersecurity", "Tech Community"]},
    {"url": "https://www.meetup.com/producttank-philadelphia/", "tags": ["Tech Skills", "Product", "UX"]},
    {"url": "https://www.meetup.com/code-coffee-philly/", "tags": ["Tech Skills", "Software Development", "Tech Community"]},
    {"url": "https://www.meetup.com/philadelphia-golang-meetup-group/", "tags": ["Tech Skills", "Software Development", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/philadelphia-rhug/", "tags": ["Tech Skills", "DevOps", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/philadelphia-apache-airflow-meetup-group/", "tags": ["Tech Skills", "Data Science", "Cloud & Platform"]},
    {"url": "https://www.meetup.com/decentralized-philly/", "tags": ["Finance", "Crypto & Web3", "Tech Community"]},
    {"url": "https://luma.com/philaconvalley", "tags": ["Tech Skills", "Software Development", "Startup", "Tech Community"]},
    {"url": "https://luma.com/dingho", "tags": ["Culture", "Community"]},
    {"url": "https://luma.com/globaltechtritionistalliance", "tags": ["Tech Community", "Wellness"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-TH1lmTVVf9uMKIz", "tags": ["Tech Community", "Professional Networking", "Business"]},
    {"url": "https://luma.com/getsentry", "tags": ["Tech Skills", "Software Development", "DevOps", "Tech Community"]},
    {"url": "https://luma.com/1philadelphia", "tags": ["Startup", "Business", "Tech Community"]},
    {"url": "https://luma.com/hikeandheal", "tags": ["Wellness", "Community"]},
    {"url": "https://luma.com/ucitysquare", "tags": ["Business", "Startup", "Professional Networking"]},
    {"url": "https://luma.com/JBA", "tags": ["Youth Education", "Career Growth", "Community"]},
    {"url": "https://luma.com/letmeknowclub", "tags": ["Culture", "Community"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-XxkA8aDamQzlzeg", "tags": ["Safety & Stability", "Community"]},
    {"url": "https://luma.com/uev", "tags": ["Tech Community", "Professional Networking"]},
    {"url": "https://api.lu.ma/user/profile/events-hosting?user_api_id=usr-cWlmpHTclGHVHjr", "tags": ["Culture", "Community"]},
    {"url": "https://luma.com/fishtown.gals", "tags": ["Culture", "Community"]},
    {"url": "https://luma.com/blackhippieart", "tags": ["Culture", "Community"]},
    {"url": "https://luma.com/the-mindfultech-club", "tags": ["Tech Community", "Wellness"]},
]

apply_city_source_taxonomy(sources)
